{"uid":"a16353269b4b1198","name":"Тест успешного удаления запроса из избранного","fullName":"tests.user.test_user_api.TestUserAPI#test_remove_from_favourites_success","historyId":"ceac80401fd9e5cd9418de44e0277fcd","time":{"start":1746142753515,"stop":1746142753515,"duration":0},"description":"Проверяем удаление ранее добавленного элемента из избранного.","descriptionHtml":"<p>Проверяем удаление ранее добавленного элемента из избранного.</p>\n","status":"failed","statusMessage":"Failed: КРИТИЧЕСКАЯ ОШИБКА: He удалось выполнить сессионный логин для пользователя testUser4@test.com. Ошибка: The status was pending 200, but received 500. URL: http://localhost:4040/api/auth\nBody of the answer:\nPlanned Server Error","statusTrace":"The status was pending 200, but received 500. URL: http://localhost:4040/api/auth\nBody of the answer:\nPlanned Server Error\n\nDuring handling of the above exception, another exception occurred:\nКРИТИЧЕСКАЯ ОШИБКА: He удалось выполнить сессионный логин для пользователя testUser4@test.com. Ошибка: The status was pending 200, but received 500. URL: http://localhost:4040/api/auth\nBody of the answer:\nPlanned Server Error","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"delete_output_dir","time":{"start":1746142751099,"stop":1746142751100,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"pytestconfig","time":{"start":1746142751099,"stop":1746142751099,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"_verify_url","time":{"start":1746142751100,"stop":1746142751100,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"base_url","time":{"start":1746142751100,"stop":1746142751100,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"playwright_instance","time":{"start":1746142751100,"stop":1746142751613,"duration":513},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"api_request_context","time":{"start":1746142751614,"stop":1746142751641,"duration":27},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"http_client","time":{"start":1746142751642,"stop":1746142751642,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"auth_client","time":{"start":1746142751643,"stop":1746142751643,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"auth_token","time":{"start":1746142753517,"stop":1746142753589,"duration":72},"status":"failed","statusMessage":"Failed: КРИТИЧЕСКАЯ ОШИБКА: He удалось выполнить сессионный логин для пользователя testUser4@test.com. Ошибка: The status was pending 200, but received 500. URL: http://localhost:4040/api/auth\nBody of the answer:\nPlanned Server Error\n","statusTrace":"  File \"/app/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"/app/.venv/lib/python3.13/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/app/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/app/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/app/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/app/tests/conftest.py\", line 109, in auth_token_fixture\n    pytest.fail(\n    ~~~~~~~~~~~^\n        f\"КРИТИЧЕСКАЯ ОШИБКА: He удалось выполнить сессионный логин для пользователя \"\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        f\"{TEST_USER_LOGIN}. Ошибка: {e}\",\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        pytrace=False,\n        ^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/app/.venv/lib/python3.13/site-packages/_pytest/outcomes.py\", line 178, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n","steps":[],"attachments":[{"uid":"6bab6757ec9fd762","name":"Status Code: 500","source":"6bab6757ec9fd762.txt","type":"text/plain","size":3},{"uid":"2f83a684b42c7372","name":"Request URL","source":"2f83a684b42c7372.uri","type":"text/uri-list","size":30},{"uid":"c7f6c090f5885363","name":"Response Headers (JSON)","source":"c7f6c090f5885363.json","type":"application/json","size":309},{"uid":"c8f035e98620cd25","name":"Response Body (Text)","source":"c8f035e98620cd25.txt","type":"text/plain","size":20},{"uid":"b7b9c4a018fde54d","name":"Status response code: 500 (Expected: 200)","source":"b7b9c4a018fde54d.txt","type":"text/plain","size":3}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":5,"hasContent":true,"attachmentStep":false},{"name":"auth_token","time":{"start":1746142753612,"stop":1746142753716,"duration":104},"status":"passed","steps":[],"attachments":[{"uid":"506027fb88ae992f","name":"Status Code: 200","source":"506027fb88ae992f.txt","type":"text/plain","size":3},{"uid":"4b05a43c0a8fb72d","name":"Request URL","source":"4b05a43c0a8fb72d.uri","type":"text/uri-list","size":30},{"uid":"6135e17f8f84795a","name":"Response Headers (JSON)","source":"6135e17f8f84795a.json","type":"application/json","size":317},{"uid":"76846da0a5e15bbb","name":"Response Body (JSON)","source":"76846da0a5e15bbb.json","type":"application/json","size":224},{"uid":"b612a4e8f5d9e579","name":"Status response code: 200 (Expected: 200)","source":"b612a4e8f5d9e579.txt","type":"text/plain","size":3},{"uid":"6681269c919c843f","name":"Body of the answer (failed by AuthSuccessResponse)","source":"6681269c919c843f.json","type":"application/json","size":220}],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":6,"hasContent":true,"attachmentStep":false},{"name":"authenticated_api_req_context","time":{"start":1746142753716,"stop":1746142753733,"duration":17},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"authenticated_http_client","time":{"start":1746142753733,"stop":1746142753733,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"authenticated_user_client","time":{"start":1746142753733,"stop":1746142753733,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"setup_favourite","time":{"start":1746142753734,"stop":1746142753811,"duration":77},"status":"skipped","statusMessage":"Skipped: He удалось добавить элемент в избранное для тестов удаления: The status was pending 200, but received 400. URL: http://localhost:4040/api/user/favourites\nBody of the answer:\nFailed to add request to favourites\n","statusTrace":"  File \"/app/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"/app/.venv/lib/python3.13/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/app/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/app/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/app/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/app/tests/user/conftest.py\", line 28, in setup_favourite\n    pytest.skip(f\"He удалось добавить элемент в избранное для тестов удаления: {e}\")\n    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/app/.venv/lib/python3.13/site-packages/_pytest/outcomes.py\", line 160, in skip\n    raise Skipped(msg=reason, allow_module_level=allow_module_level)\n","steps":[{"name":"Добавление запроса в избранное","time":{"start":1746142753734,"stop":1746142753809,"duration":75},"status":"failed","statusMessage":"AssertionError: The status was pending 200, but received 400. URL: http://localhost:4040/api/user/favourites\nBody of the answer:\nFailed to add request to favourites\n","statusTrace":"  File \"/app/.venv/lib/python3.13/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"/app/api/user/client.py\", line 63, in add_to_favourites\n    processed_response = self._handle_response(response, expected_status)\n  File \"/app/api/base_api.py\", line 69, in _handle_response\n    assert response.status == expected_status, (\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","steps":[],"attachments":[{"uid":"1a6872b469055ac1","name":"Status Code: 400","source":"1a6872b469055ac1.txt","type":"text/plain","size":3},{"uid":"5df53d2b6cd7aa2c","name":"Request URL","source":"5df53d2b6cd7aa2c.uri","type":"text/uri-list","size":41},{"uid":"8c93359684c00290","name":"Response Headers (JSON)","source":"8c93359684c00290.json","type":"application/json","size":309},{"uid":"b33594eb2b096005","name":"Response Body (Text)","source":"b33594eb2b096005.txt","type":"text/plain","size":35},{"uid":"eda0fa249a070a93","name":"Status response code: 400 (Expected: 200)","source":"eda0fa249a070a93.txt","type":"text/plain","size":3}],"parameters":[{"name":"payload","value":"AddToFavouritesPayload(request_id='test-fav-3b2a8bbf-4b86-4613-adb6-afce5a206b73')"},{"name":"expected_status","value":"200"}],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":5,"hasContent":true,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":1,"attachmentsCount":5,"hasContent":true,"attachmentStep":false}],"testStage":{"description":"Проверяем удаление ранее добавленного элемента из избранного.","status":"failed","statusMessage":"Failed: КРИТИЧЕСКАЯ ОШИБКА: He удалось выполнить сессионный логин для пользователя testUser4@test.com. Ошибка: The status was pending 200, but received 500. URL: http://localhost:4040/api/auth\nBody of the answer:\nPlanned Server Error","statusTrace":"The status was pending 200, but received 500. URL: http://localhost:4040/api/auth\nBody of the answer:\nPlanned Server Error\n\nDuring handling of the above exception, another exception occurred:\nКРИТИЧЕСКАЯ ОШИБКА: He удалось выполнить сессионный логин для пользователя testUser4@test.com. Ошибка: The status was pending 200, but received 500. URL: http://localhost:4040/api/auth\nBody of the answer:\nPlanned Server Error","steps":[],"attachments":[{"uid":"4ba16045726266ee","name":"log","source":"4ba16045726266ee.txt","type":"text/plain","size":495},{"uid":"63df9777f97720f","name":"stderr","source":"63df9777f97720f.txt","type":"text/plain","size":583}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":2,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"authenticated_api_req_context::0","time":{"start":1746142753819,"stop":1746142753835,"duration":16},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"api_request_context::0","time":{"start":1746142754655,"stop":1746142754671,"duration":16},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"playwright_instance::0","time":{"start":1746142754672,"stop":1746142754683,"duration":11},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"feature","value":"Избранное пользователя (DELETE /api/user/favourites/{id})"},{"name":"epic","value":"Управление пользователем"},{"name":"severity","value":"normal"},{"name":"story","value":"Удаление из избранного"},{"name":"tag","value":"@pytest.mark.usefixtures('setup_favourite')"},{"name":"tag","value":"positive"},{"name":"tag","value":"user"},{"name":"parentSuite","value":"tests.user"},{"name":"suite","value":"test_user_api"},{"name":"subSuite","value":"TestUserAPI"},{"name":"host","value":"fv-az523-139"},{"name":"thread","value":"6-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.user.test_user_api"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":["@pytest.mark.usefixtures('setup_favourite')","positive","user"]},"source":"a16353269b4b1198.json","parameterValues":[]}