2025-05-05 22:20:18 [INFO] tests.request.conftest: Создание UserClient... [conftest.py:14]
2025-05-05 22:20:18 [INFO] tests.request.test_request_api: Тест: Внесение вклада в несуществующий запрос (POST /api/request/non-existent-fb4171f6-6271-4e45-a8d7-afa746612dbf/contribution) [test_request_api.py:220]
2025-05-05 22:20:18 [INFO] api.request.client: Вызов POST /api/request/non-existent-fb4171f6-6271-4e45-a8d7-afa746612dbf/contribution [client.py:79]
2025-05-05 22:20:18 [INFO] core.http_client: Sending POST request to /api/request/non-existent-fb4171f6-6271-4e45-a8d7-afa746612dbf/contribution [http_client.py:73]
2025-05-05 22:20:18 [INFO] core.http_client: Received response 403 from http://localhost:4040/api/request/non-existent-fb4171f6-6271-4e45-a8d7-afa746612dbf/contribution [http_client.py:80]
2025-05-05 22:20:19 [INFO] tests.request.test_request_api: Тест: Внесение вклада в несуществующий запрос (POST /api/request/non-existent-fb4171f6-6271-4e45-a8d7-afa746612dbf/contribution) [test_request_api.py:220]
2025-05-05 22:20:19 [INFO] api.request.client: Вызов POST /api/request/non-existent-fb4171f6-6271-4e45-a8d7-afa746612dbf/contribution [client.py:79]
2025-05-05 22:20:19 [INFO] core.http_client: Sending POST request to /api/request/non-existent-fb4171f6-6271-4e45-a8d7-afa746612dbf/contribution [http_client.py:73]
2025-05-05 22:20:19 [INFO] core.http_client: Received response 403 from http://localhost:4040/api/request/non-existent-fb4171f6-6271-4e45-a8d7-afa746612dbf/contribution [http_client.py:80]
2025-05-05 22:20:19 [INFO] tests.request.test_request_api: Тест: Внесение вклада в несуществующий запрос (POST /api/request/non-existent-fb4171f6-6271-4e45-a8d7-afa746612dbf/contribution) [test_request_api.py:220]
2025-05-05 22:20:19 [INFO] api.request.client: Вызов POST /api/request/non-existent-fb4171f6-6271-4e45-a8d7-afa746612dbf/contribution [client.py:79]
2025-05-05 22:20:19 [INFO] core.http_client: Sending POST request to /api/request/non-existent-fb4171f6-6271-4e45-a8d7-afa746612dbf/contribution [http_client.py:73]
2025-05-05 22:20:19 [INFO] core.http_client: Received response 403 from http://localhost:4040/api/request/non-existent-fb4171f6-6271-4e45-a8d7-afa746612dbf/contribution [http_client.py:80]
