2025-09-18 21:49:09 [INFO] tests.request.conftest: Создание UserClient... [conftest.py:14]
2025-09-18 21:49:09 [INFO] tests.request.test_request_api: Тест: Внесение вклада в несуществующий запрос (POST /api/request/non-existent-06ccc3a3-8945-45f2-8e1a-a7db93f804d8/contribution) [test_request_api.py:220]
2025-09-18 21:49:09 [INFO] api.request.client: Вызов POST /api/request/non-existent-06ccc3a3-8945-45f2-8e1a-a7db93f804d8/contribution [client.py:79]
2025-09-18 21:49:09 [INFO] core.http_client: Sending POST request to /api/request/non-existent-06ccc3a3-8945-45f2-8e1a-a7db93f804d8/contribution [http_client.py:73]
2025-09-18 21:49:09 [INFO] core.http_client: Received response 403 from http://localhost:4040/api/request/non-existent-06ccc3a3-8945-45f2-8e1a-a7db93f804d8/contribution [http_client.py:80]
2025-09-18 21:49:09 [INFO] tests.request.test_request_api: Тест: Внесение вклада в несуществующий запрос (POST /api/request/non-existent-06ccc3a3-8945-45f2-8e1a-a7db93f804d8/contribution) [test_request_api.py:220]
2025-09-18 21:49:09 [INFO] api.request.client: Вызов POST /api/request/non-existent-06ccc3a3-8945-45f2-8e1a-a7db93f804d8/contribution [client.py:79]
2025-09-18 21:49:09 [INFO] core.http_client: Sending POST request to /api/request/non-existent-06ccc3a3-8945-45f2-8e1a-a7db93f804d8/contribution [http_client.py:73]
2025-09-18 21:49:09 [INFO] core.http_client: Received response 403 from http://localhost:4040/api/request/non-existent-06ccc3a3-8945-45f2-8e1a-a7db93f804d8/contribution [http_client.py:80]
2025-09-18 21:49:09 [INFO] tests.request.test_request_api: Тест: Внесение вклада в несуществующий запрос (POST /api/request/non-existent-06ccc3a3-8945-45f2-8e1a-a7db93f804d8/contribution) [test_request_api.py:220]
2025-09-18 21:49:09 [INFO] api.request.client: Вызов POST /api/request/non-existent-06ccc3a3-8945-45f2-8e1a-a7db93f804d8/contribution [client.py:79]
2025-09-18 21:49:09 [INFO] core.http_client: Sending POST request to /api/request/non-existent-06ccc3a3-8945-45f2-8e1a-a7db93f804d8/contribution [http_client.py:73]
2025-09-18 21:49:09 [INFO] core.http_client: Received response 403 from http://localhost:4040/api/request/non-existent-06ccc3a3-8945-45f2-8e1a-a7db93f804d8/contribution [http_client.py:80]
