2025-05-04 22:42:06 [INFO] tests.request.conftest: Создание UserClient... [conftest.py:14]
2025-05-04 22:42:06 [INFO] tests.request.test_request_api: Тест: Успешное получение всех запросов (GET /api/request) [test_request_api.py:45]
2025-05-04 22:42:06 [INFO] api.request.client: Вызов GET /api/request [client.py:28]
2025-05-04 22:42:06 [INFO] core.http_client: Sending GET request to /api/request with params: None [http_client.py:44]
2025-05-04 22:42:06 [INFO] core.http_client: Received response 403 from http://localhost:4040/api/request [http_client.py:48]
2025-05-04 22:42:06 [INFO] tests.request.test_request_api: Тест: Успешное получение всех запросов (GET /api/request) [test_request_api.py:45]
2025-05-04 22:42:06 [INFO] api.request.client: Вызов GET /api/request [client.py:28]
2025-05-04 22:42:06 [INFO] core.http_client: Sending GET request to /api/request with params: None [http_client.py:44]
2025-05-04 22:42:06 [INFO] core.http_client: Received response 403 from http://localhost:4040/api/request [http_client.py:48]
2025-05-04 22:42:06 [INFO] tests.request.test_request_api: Тест: Успешное получение всех запросов (GET /api/request) [test_request_api.py:45]
2025-05-04 22:42:06 [INFO] api.request.client: Вызов GET /api/request [client.py:28]
2025-05-04 22:42:06 [INFO] core.http_client: Sending GET request to /api/request with params: None [http_client.py:44]
2025-05-04 22:42:06 [INFO] core.http_client: Received response 403 from http://localhost:4040/api/request [http_client.py:48]
2025-05-04 22:42:06 [INFO] tests.request.test_request_api: Тест: Успешное получение всех запросов (GET /api/request) [test_request_api.py:45]
2025-05-04 22:42:06 [INFO] api.request.client: Вызов GET /api/request [client.py:28]
2025-05-04 22:42:06 [INFO] core.http_client: Sending GET request to /api/request with params: None [http_client.py:44]
2025-05-04 22:42:06 [INFO] core.http_client: Received response 403 from http://localhost:4040/api/request [http_client.py:48]
