2025-05-05 23:40:03 [INFO] core.mock_http_client: MockHTTPClient ID 140325788878800 инициализирован. Mocks: {} [mock_http_client.py:24]
2025-05-05 23:40:03 [INFO] tests.auth.test_auth_mocked: Тест: Неверные логин и пароль (Мок Factory) [test_auth_mocked.py:97]
2025-05-05 23:40:03 [INFO] core.mock_http_client: MockHTTPClient ID 140325788878800 установил мок для: 'POST:/api/auth' (Статус: 400). Текущие моки: ['POST:/api/auth'] [mock_http_client.py:108]
2025-05-05 23:40:03 [INFO] core.mock_http_client: MockHTTPClient ID 140325788878800 ищет мок для ключа: 'POST:/api/auth'. Текущие моки: ['POST:/api/auth'] [mock_http_client.py:36]
2025-05-05 23:40:03 [INFO] core.mock_http_client: Найден и возвращен мок для: POST:/api/auth [mock_http_client.py:44]
2025-05-05 23:40:03 [INFO] tests.auth.test_auth_mocked: Мок-ответ 400 (неверные креды) успешно обработан. [test_auth_mocked.py:113]
2025-05-05 23:40:03 [INFO] core.mock_http_client: MockHTTPClient ID 140325788878800 очищает моки. Было: ['POST:/api/auth'] [mock_http_client.py:118]
